  ScrollReveal().reveal('header');
  ScrollReveal().reveal('.textos', { delay: 500 });
  ScrollReveal().reveal('.subtitulo', { delay: 500 });
  ScrollReveal().reveal('.boton', { delay: 500 });
  ScrollReveal().reveal('.acerca-de',{ delay: 500});
  ScrollReveal().reveal('.sobre-nosotros',{ delay: 500});
  ScrollReveal().reveal('.slogan',{ delay: 500});
  ScrollReveal().reveal('.parrafo',{ delay: 500});
  ScrollReveal().reveal('.galeria',{ delay: 500});
  ScrollReveal().reveal('.imagenes',{ delay: 500});
  ScrollReveal().reveal('.imagenes-none',{ delay: 500});
  ScrollReveal().reveal('.miembros',{ delay: 500});
  ScrollReveal().reveal('.cliente',{ delay: 500});
  ScrollReveal().reveal('.titulo-footer',{ delay: 500});
  ScrollReveal().reveal('.subtitulo-footer',{ delay: 500});
  ScrollReveal().reveal('.footer',{ delay: 500});